import type { Metadata } from "next";
import './global.css'
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '@/components/layout/Navbar'
import Footer  from "@/components/layout/Footer";
import { Providers } from "@/components/layout/ThemeProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product management",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
          <div className="flex flex-col min-h-screen">
            <Providers>
            <Navbar/>
           <main className="flex-1">
            {children}
           </main>
           <Footer/>
          </Providers>
          </div>
      </body>
    </html>
  );
}
