import type { Metadata } from "next";
import "./global.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/store/Navbar";
import Footer from "@/components/store/Footer";
import { Providers } from "@/components/store/ThemeProvider";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";
// import ToasterProvider from "@/components/ui/ToasterProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

 <Toaster
      position="top-right"
      toastOptions={{
        duration: 2000,
        style: {
          borderRadius: "10px",
          fontSize: "14px",
        },
      }}
    />        
    <div className="flex flex-col min-h-screen">
          <Providers>
            <AuthProvider>
              <CartProvider>
                <Navbar />
                <main className="flex-1">{children}</main>
                <Footer />
              </CartProvider>
            </AuthProvider>
          </Providers>
        </div>
      </body>
    </html>
  );
}
